kind: pipeline
name: Build & Deploy

steps:
  - name: build preview
    image: docker/compose:1.24.1
    environment:
      REACT_APP_STRIPE_API_KEY:
        from_secret: REACT_APP_STRIPE_API_KEY
      REACT_APP_MONGO_URL:
        from_secret: REACT_APP_MONGO_URL
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker image prune
#      - docker-compose build preview
    depends_on:
      - clone
  - name: deploy preview
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-app up -d preview
    depends_on:
      - build preview
  - name: build production
    image: docker/compose:1.24.1
    environment:
      REACT_APP_STRIPE_API_KEY:
        from_secret: REACT_APP_STRIPE_API_KEY
      REACT_APP_MONGO_URL:
        from_secret: REACT_APP_MONGO_URL
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose build production
    when:
      branch:
        - master
    depends_on:
      - clone
  - name: deploy production
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-app up -d production
    when:
      branch:
        - master
    depends_on:
      - build production

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
