
export default {
  mobile: {
    visitors: [
      { to: '/company/presentation', label: 'Entreprise' },
      { to: '/individual/presentation', label: 'Particulier' },
      { to: '/individual/prices', label: 'Coût' },
      { to: '/hives', label: 'Les ruches de nos mécènes' },
      { to: '/adherer', label: 'Adhérer' },
      { to: '/visites', label: 'Participer aux visites' },
      { to: '/formations', label: 'Se former' },
      { to: 'https://shop.confidencesdabeilles.fr/blogs/all/que-planter-pour-aider-les-abeilles', label: 'Planter pour aider les abeilles', external: true },
      { to: '/ressources', label: 'Ressources' },
      { to: '/presentation', label: 'La video' },
      { to: '/about', label: 'L\'histoire' },
      { to: '/team', label: 'L\'équipe et le conseil d\'administration' },
      { to: '/partners', label: 'Partenaires' },
      { to: '/rapports-activite', label: 'Les rapports d\'activité' },
      { to: '/jobs', label: 'Rejoindre l\'aventure' },
      { to: '/contact', label: 'Contact' },
      { to: '/faq', label: 'FAQ' },
      { to: '/login', label: 'Se connecter' },
      { to: '/presignup', label: 'Créer un compte' },
    ],
    loggedIn: [
      { to: '/company/presentation', label: 'Entreprise' },
      { to: '/individual/presentation', label: 'Particulier' },
      { to: '/individual/prices', label: 'Coût' },
      { to: '/hives', label: 'Les ruches de nos mécènes' },
      { to: '/adherer', label: 'Adhérer' },
      { to: '/visites', label: 'Participer aux visites' },
      { to: '/formations', label: 'Se former' },
      { to: 'https://shop.confidencesdabeilles.fr/blogs/all/que-planter-pour-aider-les-abeilles', label: 'Planter pour aider les abeilles', external: true },
      { to: '/ressources', label: 'Ressources' },
      { to: '/presentation', label: 'La video' },
      { to: '/about', label: 'L\'histoire' },
      { to: '/team', label: 'L\'équipe et le conseil d\'administration' },
      { to: '/partners', label: 'Partenaires' },
      { to: '/rapports-activite', label: 'Les rapports d\'activité' },
      { to: '/jobs', label: 'Rejoindre l\'aventure' },
      { to: '/contact', label: 'Contact' },
      { to: '/faq', label: 'FAQ' },
      { to: '/account', label: 'Mon compte' },
      { to: '/logout', label: 'Deconnexion' },
    ],
  },
  desktop: {
    loggedIn: [
      { to: '', label: '' },
    ],
    dropdown1: [
      { to: '/adherer', label: 'Adhérer' },
      { to: '/visites', label: 'Participer aux visites' },
      { to: '/formations', label: 'Se former' },
      { to: 'https://shop.confidencesdabeilles.fr/blogs/all/que-planter-pour-aider-les-abeilles', label: 'Planter pour aider les abeilles', external: true },
      { to: '/ressources', label: 'Ressources' },
    ],
    dropdown2: [
      { to: '/presentation', label: 'La video' },
      { to: '/about', label: 'L\'histoire' },
      { to: '/team', label: 'L\'équipe et le conseil d\'administration' },
      { to: '/partners', label: 'Partenaires' },
      { to: '/rapports-activite', label: 'Les rapports d\'activité' },
      { to: '/jobs', label: 'Rejoindre l\'aventure' },
      { to: '/contact', label: 'Contact' },
      { to: '/faq', label: 'FAQ' },
    ],
    visitors: [
      { to: '/company/presentation', label: 'Entreprise' },
      { to: '/individual/presentation', label: 'Particulier' },
      { to: '/individual/prices', label: 'Coût' },
      { to: '/hives', label: 'Les ruches de nos mécènes' },
    ],
  },
};
